version: '2'
services:
  keepalived:
    container_name: docker-lb
    restart: always
    ports:
      - "8080:8080"
      - "443:443"
      - "60001:60001"
      - "1936:1936"
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      VIP: 192.168.1.140
      MASK: 32
      VROUTERID: 2
      STATE: BACKUP
      INTERFACE: eth0
      PRIORITY: 100
      ADVERT: 1
      AUTHPASS: test12
    image: lukaszbielinski/docker-lb:1.0
    volumes:
     - /root/haproxy.cfg:/haproxy.cfg
